#! /bin/sh
bspc monitor -d  one two three four five 

bspc config border_width         5
bspc config window_gap          10
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config single_monocle true
bspc config borderless_monocle true 
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#3a3a3a"
bspc config focused_border_color "#5a5a5a"
bspc config urgent_border_color "#ff5555"
bspc config presel_feedback_color "#f1fa8c"

xsetroot -cursor_name left_ptr &
flameshot >/dev/null 2>&1& 
setxkbmap -layout "us,ru" -option grp:alt_shift_toggle &
hsetroot -solid "#1f1f1f" &
picom --config /home/uzzer/src/comp.conf &
polybar bar &
sxhkd &
